name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - .gitignore

env:
  PHASE: prod
  APP_NAME: diribon2gg
  AWS_REGION: ap-northeast-2
  AWS_ROLE: arn:aws:iam::881490123244:role/github-cicd-suminhong
  ECR_REPOSITORY: suminhong/diribon2gg
  ECR_REGISTRY: 881490123244.dkr.ecr.ap-northeast-2.amazonaws.com
  GITHUB_USERNAME: ${{ secrets.GH_ACTOR }}
  GITHUB_PASSWORD: ${{ secrets.GH_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 리포지토리 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # AWS 자격 증명
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: ${{ env.APP_NAME }}-${{ env.PHASE }}
          aws-region: ${{ env.AWS_REGION }}

      # ECR 생성 또는 업데이트
      - name: Create or Update ECR Repo
        uses: MarryMeAI/cicd/ecr-create@main
        with:
          ecr_repository: ${{ env.ECR_REPOSITORY }}

      # 이미지 태그 설정 (타임스탬프 기반)
      - name: Set ImageTag by Timestamp
        id: set_image_tag
        run: |
          echo "image_tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      
      # ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 이미지 빌드 및 푸시
      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ env.image_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # HEAD 커밋 제목 가져오기
      - name: Get Head Commit Title
        run: echo "commit_title=$(git log --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_ENV

    #   # ArgoCD 배포 트리거 실행
    #   - name: CD-Trigger
    #     uses: MarryMeAI/cicd-action/cd-trigger@main
    #     with:
    #       app_path: ${{ env.ECR_REPOSITORY }}
    #       phase: ${{ env.PHASE }}
    #       ecr_repository: ${{ env.ECR_REPOSITORY }}
    #       image_tag: ${{ env.image_tag }}
    #       pusher_name: ${{ github.event.sender.login }}
    #       head_commit: ${{ env.commit_title }}